apiVersion: v1
kind: Service
metadata:
  name: zemo-v2-service
  namespace: zemo-v2
  labels:
    app: zemo-v2
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 7000
    protocol: TCP
    name: http
  selector:
    app: zemo-v2
