apiVersion: v1
kind: Service
metadata:
  name: aemo-v2ZZ-service
  namespace: aemo-v2ZZ
  labels:
    app: aemo-v2ZZ
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 7000
    protocol: TCP
    name: http
  selector:
    app: aemo-v2ZZ
