apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aemo-v4PP-gateway
  namespace: aemo-v4PP
  annotations:
    # regex: /api/aemo-v4PP/api/<rest> -> /api/<rest>
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: "/api/$2"
spec:
  ingressClassName: nginx
  rules:
  - host: gateway.local
    http:
      paths:
      - path: /api/aemo-v4PP/api(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: aemo-v4PP-service
            port:
              number: 80
  - host: localhost
    http:
      paths:
      - path: /api/aemo-v4PP/api(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: aemo-v4PP-service
            port:
              number: 80
