apiVersion: v1
kind: Service
metadata:
  name: aemo-v2L-service
  namespace: aemo-v2L
  labels:
    app: aemo-v2L
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 7000
    protocol: TCP
    name: http
  selector:
    app: aemo-v2L
