apiVersion: v1
kind: Service
metadata:
  name: zemo-v4r-service
  namespace: zemo-v4r
  labels:
    app: zemo-v4r
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5001
    protocol: TCP
    name: http
  selector:
    app: zemo-v4r
