apiVersion: v1
kind: Service
metadata:
  name: zemo-v4-service
  namespace: zemo-v4
  labels:
    app: zemo-v4
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5001
    protocol: TCP
    name: http
  selector:
    app: zemo-v4
