apiVersion: v1
kind: Service
metadata:
  name: zemo-v6e-service
  namespace: zemo-v6e
  labels:
    app: zemo-v6e
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5001
    protocol: TCP
    name: http
  selector:
    app: zemo-v6e
